# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QtProjects\压水堆核电厂二回路热力系统初步设计(V1.0)\newPro.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newPro(object):
    def setupUi(self, newPro):
        newPro.setObjectName("newPro")
        newPro.resize(434, 176)
        self.label = QtWidgets.QLabel(newPro)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(newPro)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(newPro)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 281, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(newPro)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 391, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(newPro)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 110, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(newPro)
        self.buttonBox.setGeometry(QtCore.QRect(210, 140, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(newPro)
        QtCore.QMetaObject.connectSlotsByName(newPro)

    def retranslateUi(self, newPro):
        _translate = QtCore.QCoreApplication.translate
        newPro.setWindowTitle(_translate("newPro", "新建项目文件夹"))
        self.label.setText(_translate("newPro", "文件夹名："))
        self.label_2.setText(_translate("newPro", "文件夹路径："))
        self.pushButton_2.setText(_translate("newPro", "选择路径"))
