# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QtProjects\压水堆核电厂二回路热力系统初步设计(V1.0)\exist.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exist(object):
    def setupUi(self, exist):
        exist.setObjectName("exist")
        exist.resize(400, 142)
        self.buttonBox = QtWidgets.QDialogButtonBox(exist)
        self.buttonBox.setGeometry(QtCore.QRect(40, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(exist)
        self.label.setGeometry(QtCore.QRect(90, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(exist)
        self.buttonBox.accepted.connect(exist.accept)
        self.buttonBox.rejected.connect(exist.reject)
        QtCore.QMetaObject.connectSlotsByName(exist)

    def retranslateUi(self, exist):
        _translate = QtCore.QCoreApplication.translate
        exist.setWindowTitle(_translate("exist", "Exist"))
        self.label.setText(_translate("exist", "文件已存在，是否覆盖？"))
