# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QtProjects\压水堆核电厂二回路热力系统初步设计(V1.0)\parTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parTab(object):
    def setupUi(self, parTab):
        parTab.setObjectName("parTab")
        parTab.resize(958, 731)
        self.gridLayout = QtWidgets.QGridLayout(parTab)
        self.gridLayout.setObjectName("gridLayout")
        self.parTable_left = QtWidgets.QTableWidget(parTab)
        self.parTable_left.setRowCount(0)
        self.parTable_left.setColumnCount(2)
        self.parTable_left.setObjectName("parTable_left")
        item = QtWidgets.QTableWidgetItem()
        self.parTable_left.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parTable_left.setHorizontalHeaderItem(1, item)
        self.parTable_left.horizontalHeader().setDefaultSectionSize(205)
        self.gridLayout.addWidget(self.parTable_left, 1, 0, 6, 1)
        self.pushButton_save = QtWidgets.QPushButton(parTab)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 3, 1, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(parTab)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.parTable_right = QtWidgets.QTableWidget(parTab)
        self.parTable_right.setShowGrid(True)
        self.parTable_right.setWordWrap(True)
        self.parTable_right.setCornerButtonEnabled(True)
        self.parTable_right.setRowCount(0)
        self.parTable_right.setColumnCount(2)
        self.parTable_right.setObjectName("parTable_right")
        item = QtWidgets.QTableWidgetItem()
        self.parTable_right.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parTable_right.setHorizontalHeaderItem(1, item)
        self.parTable_right.horizontalHeader().setDefaultSectionSize(205)
        self.gridLayout.addWidget(self.parTable_right, 1, 1, 1, 1)

        self.retranslateUi(parTab)
        QtCore.QMetaObject.connectSlotsByName(parTab)

    def retranslateUi(self, parTab):
        _translate = QtCore.QCoreApplication.translate
        parTab.setWindowTitle(_translate("parTab", "Form"))
        item = self.parTable_left.horizontalHeaderItem(0)
        item.setText(_translate("parTab", "参数"))
        item = self.parTable_left.horizontalHeaderItem(1)
        item.setText(_translate("parTab", "数值"))
        self.pushButton_save.setText(_translate("parTab", "保存"))
        self.pushButton_run.setText(_translate("parTab", "运行"))
        self.label.setText(_translate("parTab", "附表1：已知条件"))
        self.label_2.setText(_translate("parTab", "附表2：主要热力参数"))
        item = self.parTable_right.horizontalHeaderItem(0)
        item.setText(_translate("parTab", "参数"))
        item = self.parTable_right.horizontalHeaderItem(1)
        item.setText(_translate("parTab", "数值"))
