# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QtProjects\压水堆核电厂二回路热力系统初步设计(V1.0)\outTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_outTab(object):
    def setupUi(self, outTab):
        outTab.setObjectName("outTab")
        outTab.resize(959, 730)
        self.gridLayout = QtWidgets.QGridLayout(outTab)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(outTab)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.pushButton_py = QtWidgets.QPushButton(outTab)
        self.pushButton_py.setObjectName("pushButton_py")
        self.gridLayout.addWidget(self.pushButton_py, 1, 0, 1, 1)

        self.retranslateUi(outTab)
        QtCore.QMetaObject.connectSlotsByName(outTab)

    def retranslateUi(self, outTab):
        _translate = QtCore.QCoreApplication.translate
        outTab.setWindowTitle(_translate("outTab", "Form"))
        self.pushButton_py.setText(_translate("outTab", "生成Python代码"))
